import StudentImage from "../assets/studentImg.png";
export const StudentsLists = [
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    familyId: "4543",
    studentId: "4543",
    name: "Asim warrich",
    familyName: "Hammad habib",
    student: "5",
    fee: "6500",
    images: StudentImage,
    submited: "6 Nov 2023",
    dob: "24 - 11 - 1996",
    class: "10th",
    section: "A",
    status: "Active",
    address:
      "Robert Robertson Robert RobertsonRobert RobertsonRobert RobertsonRobert Robertson ",
    note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
];
